# Created by :
   - Debjeet das



# Scrapping Data from Naukri.com :
   - We are using BeautifulSoup for extracting the data.
   - And selenium for making a full functional web page to be controlled from  a remote user to perform some actions on the website.
   - And finally we will create a dataframe which will contain all the informations scrapped from all the pages of the website.

In [65]:
# Installing selenium

!pip install selenium

Requirement already satisfied: selenium in c:\users\debje\anaconda3\lib\site-packages (3.141.0)
Requirement already satisfied: urllib3 in c:\users\debje\anaconda3\lib\site-packages (from selenium) (1.24.1)

In [1]:
# Importing webdriver in order open the default browser as Firefox for data scrapping.

from selenium import webdriver
import os

# This is the path where the gecko driver is present so as to connect to the web server  using selenium
path_to_unzipfile= "C:\\Users\\Debjeet Das\\Desktop\\PYTHON"
os.chdir(path_to_unzipfile)

# Creating a default browser which will be used when we want to scrape data from a website
browser= webdriver.Firefox(path_to_unzipfile)

In [4]:
# Here we Scrapping data from naukri.com


# This is the URL of the webpage from where we want to scrape the data
url = "https://www.naukri.com/data-science-jobs"   
browser.get(url)

# Fetching the source page content which will be used for parsing using bs4 library
html=browser.page_source

## Parsing the Source Code :
  - Here we are importing the bs4 library which will help us to scrape the data.
  - Now the objective is to make the source code of the webpage parsable.
  - Making it parsable will help us to fetch the desired data and can be further used for analytics.
  - After that we will make a soup component which will contain the parsable source code of the web page.

In [34]:
# importing bs4
import bs4

# making a soup component which will contain the parsable html source code of the web page to be scrapped
soup=bs4.BeautifulSoup(html,"html.parser")

## Scrapping Data :
   - The first step is to go to the browser from where we are scrapping the data and look at its source code.
   - Then we need to inspect the elements we want to fetch from the source code.
   - Now the source code cosists of html tags, class and attributes which we are concerned about for scrapping.
   - Each element will reside inside a parent tag or children of that parrent tag.
   - There will be class defined for the elements to be fetched also with id which will be unique for all, along with some attributes.
   - So now we will scrape the data which has information about the various data science jobs available and some other parameters related to it.


## Elements to be scrapped :
   - We will scrape the designations offered by different companies.
   - Job location.
   - Minimum Expirience required for them.
   - Salary offered.
   - Name of the Company offering the job.

In [6]:
# extracting designation which resides inside the tag "li" and class "desig"

# we are creating an empty list in order to append all the designation to it.
designation=[]

# we are using the find_all function to find all the tags "li" and class_= "desig" from the parsed source code.
for i in soup.find_all("li",class_="desig"):
    designation.append(i.text.strip())


# So in the above step we are fetching the designations from the source code and then appending it to the list of designations.
designation

['Manager Data Science and Analytics',
 'Data Science and Analytics',
 'Senior Software Developer - Nlp/machine Learning/data Science',
 'Machine Learning / Data Science  - USA Opportunity (H1B Transfer Only)',
 'Data Science Lead',
 'Machine Learning, Data Science Trainer',
 'Merilytics - Manager - Data Science - Iit/bits/nit',
 'Data Science Senior Advisor',
 'Director-data Science',
 'Consultant Data Science',
 'Unit Manager - Data Science & Engineering Unit/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering Unit/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering Unit/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering Unit/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering Unit/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering Unit/Senior Unit Manager',
 'Data Science and Analytics',
 'Data Science Trainer - Part Time',
 'Head of Data Science  -  Search',
 'Data Science Specialist / Sr. Data Scientist',
 'Product Manager - Data Science',
 'Data Science',
 'Data Science',
 'Data Science',
 'Data Science',
 'Data Science',
 'Head of Data Science Platform',
 'Director- Data Science',
 'Data Science Engineer',
 'Business Analyst - Data Science',
 'Senior Product Manager - Data Science/machine Learning',
 'Sr Advisor, Data Science',
 'Head of Data Science Platform',
 'Head of Data Science Platform',
 'Head of Data Science',
 'Head of Data Science',
 'Principal Engineer - Data Science /machine Learning',
 'LTI Hiring- Data Science Professionals - 7th Dec @ Chennai / Hyderabad',
 'Senior Director - Data Science',
 'Data Science Manager in at ZF',
 'Automation Test, React Native, Dev Ops and Data Science Engineers',
 'Senior Analyst, Data Science',
 'Trainer For Data Science',
 'Cluster Manager - Data Science & Engineering/Senior Cluster Manager',
 'Cluster Manager - Data Science & Engineering/Senior Cluster Manager',
 'Cluster Manager - Data Science & Engineering/Senior Cluster Manager',
 'Unit Manager - Data Science & Engineering/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering/Senior Unit Manager',
 'Unit Manager - Data Science & Engineering/Senior Unit Manager',
 'Lead - Data Science & Engineering Unit/Senior Lead - Data Science']

In [11]:
# extracting locations which resides inside the tag "span" and class "loc"

location =[]
for i in soup.find_all("span",class_="loc"):
    location.append(i.text.strip())

# this list will contain all the job locations 
location

['Hyderabad',
 'Gurgaon',
 'Bengaluru',
 'United States (U.S)',
 'Gurgaon, Chandigarh',
 'Gurgaon, Noida, Delhi NCR',
 'Hyderabad',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Gurgaon',
 'Pune(Viman Nagar)',
 'Bengaluru',
 'Bengaluru',
 'Mumbai',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Gurgaon',
 'Pune',
 'Gurgaon',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Bengaluru',
 'Pune',
 'Chennai, Hyderabad',
 'Bengaluru, Gurgaon',
 'Hyderabad',
 'Jaipur, Bengaluru',
 'Bengaluru',
 'Hosur',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Pune',
 'Pune']

In [12]:
# extracting experience which is p[resent inside the tag "span" and class "exp"
exp= []
for i in soup.find_all("span",class_="exp"):
    exp.append(i.text.split("-")[0].strip())


# this list will contain the minimum experience requirement by the companies offering the job.
exp

['10',
 '2',
 '5',
 '9',
 '6',
 '3',
 '2',
 '8',
 '8',
 '5',
 '3',
 '3',
 '3',
 '3',
 '3',
 '3',
 '2',
 '5',
 '9',
 '4',
 '2',
 '2',
 '4',
 '4',
 '4',
 '4',
 '8',
 '8',
 '3',
 '3',
 '4',
 '7',
 '8',
 '8',
 '8',
 '10',
 '2',
 '4',
 '20',
 '6',
 '1',
 '8',
 '2',
 '4',
 '4',
 '4',
 '3',
 '3',
 '3',
 '3']

In [9]:
# extracting salary offered by the companies
sal= []

# Salary offered is present inside the tag "span" and class "salary"
for i in soup.find_all("span",class_="salary"):
    sal.append(i.text.strip())

    
# this loist will contain the salaries offered by the companies for a specific job designation    
sal

['Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed',
 'Not disclosed']

In [10]:
#extracting company name or the organisation name offering the job
org= []
for i in soup.find_all("span",class_="org"):
    org.append(i.text.strip().upper())
    

    
# List containing all the Organisation names offering jobs.    
org

['NOVARTIS HEALTHCARE PVT. LTD.',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'CUNESOFT',
 'DCG DATA-CORE SYSTEMS (INDIA) PVT. LTD.',
 'MAVEN WAVE PARTNERS (INDIA)PVT. LTD.',
 'SAMATRIX CONSULTING PRIVATE LIMITED',
 'MERITUS INTELYTICS PRIVATE LIMITED',
 'DELL INTERNATIONAL SERVICES INDIA  PRIVATE LIMITED',
 'SAPIENT CONSULTING PVT. LTD',
 'DELL INTERNATIONAL SERVICES INDIA  PRIVATE LIMITED',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'MARSIAN TECHNOLOGIES LLP',
 'GO-JEK',
 'CLUSTR',
 'ALLY-EXECUTIVE',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED',
 'GO-JEK',
 'SAPIENT CONSULTING PVT. LTD',
 'EMERSON ELECTRIC CO (I) PVT LTD',
 'GARTNER INDIA RESEARCH & ADVISORY SERVICES PVT LTD',
 'MEESHO',
 'DELL INTERNATIONAL SERVICES INDIA  PRIVATE LIMITED',
 'GO-JEK',
 'GO-JEK',
 'GO-JEK',
 'GO-JEK',
 'WISSDA INC',
 'LARSEN & TOUBRO INFOTECH LIMITED',
 'NEXT LEVEL BUSINESS SERVICES',
 'ZF INDIA PRIVATE LIMITED',
 'REYBHAV TECHNOLOGIES PRIVATE LIMITED',
 'DELL INTERNATIONAL SERVICES INDIA  PRIVATE LIMITED',
 'REACHMENTOR',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD',
 'BAJAJ FINSERV LENDING LTD']

## Creating a dataframe :
   - Now we will create a dataframe from the extracted data which can be further used for analytics.
   - This dataframe consists of Company name, Salary offered, Job location and designation.

In [14]:
import pandas as pd
data2= pd.DataFrame({"company": org,"salary":sal,"experience":exp,"location":location,"designation":designation})

In [15]:
data2

,company,salary,experience,location,designation
0,NOVARTIS HEALTHCARE PVT. LTD.,Not disclosed,10,Hyderabad,Manager Data Science and Analytics
1,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
2,CUNESOFT,Not disclosed,5,Bengaluru,Senior Software Developer - Nlp/machine Learni...
3,DCG DATA-CORE SYSTEMS (INDIA) PVT. LTD.,Not disclosed,9,United States (U.S),Machine Learning / Data Science - USA Opportu...
4,MAVEN WAVE PARTNERS (INDIA)PVT. LTD.,Not disclosed,6,"Gurgaon, Chandigarh",Data Science Lead
5,SAMATRIX CONSULTING PRIVATE LIMITED,Not disclosed,3,"Gurgaon, Noida, Delhi NCR","Machine Learning, Data Science Trainer"
6,MERITUS INTELYTICS PRIVATE LIMITED,Not disclosed,2,Hyderabad,Merilytics - Manager - Data Science - Iit/bits...
7,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,8,Bengaluru,Data Science Senior Advisor
8,SAPIENT CONSULTING PVT. LTD,Not disclosed,8,Bengaluru,Director-data Science
9,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,5,Bengaluru,Consultant Data Science
10,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
11,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
12,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
13,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
14,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
15,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
16,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
17,MARSIAN TECHNOLOGIES LLP,Not disclosed,5,Pune(Viman Nagar),Data Science Trainer - Part Time
18,GO-JEK,Not disclosed,9,Bengaluru,Head of Data Science - Search
19,CLUSTR,Not disclosed,4,Bengaluru,Data Science Specialist / Sr. Data Scientist
20,ALLY-EXECUTIVE,Not disclosed,2,Mumbai,Product Manager - Data Science
21,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Bengaluru,Data Science
22,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
23,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
24,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
25,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
26,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
27,SAPIENT CONSULTING PVT. LTD,Not disclosed,8,Gurgaon,Director- Data Science
28,EMERSON ELECTRIC CO (I) PVT LTD,Not disclosed,3,Pune,Data Science Engineer
29,GARTNER INDIA RESEARCH & ADVISORY SERVICES PVT...,Not disclosed,3,Gurgaon,Business Analyst - Data Science
30,MEESHO,Not disclosed,4,Bengaluru,Senior Product Manager - Data Science/machine ...
31,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,7,Bengaluru,"Sr Advisor, Data Science"
32,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
33,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
34,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science
35,GO-JEK,Not disclosed,10,Bengaluru,Head of Data Science
36,WISSDA INC,Not disclosed,2,Pune,Principal Engineer - Data Science /machine Lea...
37,LARSEN & TOUBRO INFOTECH LIMITED,Not disclosed,4,"Chennai, Hyderabad",LTI Hiring- Data Science Professionals - 7th D...
38,NEXT LEVEL BUSINESS SERVICES,Not disclosed,20,"Bengaluru, Gurgaon",Senior Director - Data Science
39,ZF INDIA PRIVATE LIMITED,Not disclosed,6,Hyderabad,Data Science Manager in at ZF
40,REYBHAV TECHNOLOGIES PRIVATE LIMITED,Not disclosed,1,"Jaipur, Bengaluru","Automation Test, React Native, Dev Ops and Dat..."
41,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,8,Bengaluru,"Senior Analyst, Data Science"
42,REACHMENTOR,Not disclosed,2,Hosur,Trainer For Data Science
43,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
44,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
45,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
46,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
47,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
48,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
49,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Lead - Data Science & Engineering Unit/Senior ...

## Making a user defined function :
   - It will have one argument which will be the ural of the web page to be scrapped.
   - This function will extract all the information about a particular job opening when called.
   - It will open a browser, start fetching the source code and making it parsable.
   - Then will extract the information about the job openings  offered by the different companies.
   - Which will return a dataframe containing all the above information.

In [18]:
# defining functions to get salary , designation, location,compname,exp

def get_jos(x):
    
    from selenium import webdriver
    import os

    path_to_unzipfile= "C:\\Users\\Debjeet Das\\Desktop\\PYTHON"
    os.chdir(path_to_unzipfile)
    browser1= webdriver.Firefox(path_to_unzipfile)
    
    browser1.get(x)
    html=browser1.page_source
    
    import bs4
    soup=bs4.BeautifulSoup(html,"html.parser")
    
    location =[]
    for i in soup.find_all("span",class_="loc"):
        location.append(i.text.strip())
    
    designation=[]
    for i in soup.find_all("li",class_="desig"):
        designation.append(i.text.strip())
        
    exp= []
    for i in soup.find_all("span",class_="exp"):
        exp.append(i.text.split("-")[0].strip())
        
    
    sal= []
    for i in soup.find_all("span",class_="salary"):
        sal.append(i.text.strip())
        
    org= []
    for i in soup.find_all("span",class_="org"):
        org.append(i.text.strip().upper())
        
    import pandas as pd
    data2= pd.DataFrame({"company": org,"salary":sal,"experience":exp,"location":location,"designation":designation})
    
    return data2

In [19]:
# calling the user defined fuction and returning the resultant dataframe with necessary informations scrapped from the web page.
url = "https://www.naukri.com/data-science-jobs"
get_jos(url)

,company,salary,experience,location,designation
0,NOVARTIS HEALTHCARE PVT. LTD.,Not disclosed,10,Hyderabad,Manager Data Science and Analytics
1,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
2,CUNESOFT,Not disclosed,5,Bengaluru,Senior Software Developer - Nlp/machine Learni...
3,DCG DATA-CORE SYSTEMS (INDIA) PVT. LTD.,Not disclosed,9,United States (U.S),Machine Learning / Data Science - USA Opportu...
4,MAVEN WAVE PARTNERS (INDIA)PVT. LTD.,Not disclosed,6,"Gurgaon, Chandigarh",Data Science Lead
5,SAMATRIX CONSULTING PRIVATE LIMITED,Not disclosed,3,"Gurgaon, Noida, Delhi NCR","Machine Learning, Data Science Trainer"
6,MERITUS INTELYTICS PRIVATE LIMITED,Not disclosed,2,Hyderabad,Merilytics - Manager - Data Science - Iit/bits...
7,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,8,Bengaluru,Data Science Senior Advisor
8,SAPIENT CONSULTING PVT. LTD,Not disclosed,8,Bengaluru,Director-data Science
9,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,5,Bengaluru,Consultant Data Science
10,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
11,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
12,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
13,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
14,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
15,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
16,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
17,MARSIAN TECHNOLOGIES LLP,Not disclosed,5,Pune(Viman Nagar),Data Science Trainer - Part Time
18,GO-JEK,Not disclosed,9,Bengaluru,Head of Data Science - Search
19,CLUSTR,Not disclosed,4,Bengaluru,Data Science Specialist / Sr. Data Scientist
20,ALLY-EXECUTIVE,Not disclosed,2,Mumbai,Product Manager - Data Science
21,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Bengaluru,Data Science
22,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
23,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
24,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
25,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
26,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
27,SAPIENT CONSULTING PVT. LTD,Not disclosed,8,Gurgaon,Director- Data Science
28,EMERSON ELECTRIC CO (I) PVT LTD,Not disclosed,3,Pune,Data Science Engineer
29,GARTNER INDIA RESEARCH & ADVISORY SERVICES PVT...,Not disclosed,3,Gurgaon,Business Analyst - Data Science
30,MEESHO,Not disclosed,4,Bengaluru,Senior Product Manager - Data Science/machine ...
31,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,7,Bengaluru,"Sr Advisor, Data Science"
32,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
33,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
34,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science
35,GO-JEK,Not disclosed,10,Bengaluru,Head of Data Science
36,WISSDA INC,Not disclosed,2,Pune,Principal Engineer - Data Science /machine Lea...
37,LARSEN & TOUBRO INFOTECH LIMITED,Not disclosed,4,"Chennai, Hyderabad",LTI Hiring- Data Science Professionals - 7th D...
38,NEXT LEVEL BUSINESS SERVICES,Not disclosed,20,"Bengaluru, Gurgaon",Senior Director - Data Science
39,ZF INDIA PRIVATE LIMITED,Not disclosed,6,Hyderabad,Data Science Manager in at ZF
40,REYBHAV TECHNOLOGIES PRIVATE LIMITED,Not disclosed,1,"Jaipur, Bengaluru","Automation Test, React Native, Dev Ops and Dat..."
41,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,8,Bengaluru,"Senior Analyst, Data Science"
42,REACHMENTOR,Not disclosed,2,Hosur,Trainer For Data Science
43,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
44,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
45,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
46,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
47,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
48,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
49,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Lead - Data Science & Engineering Unit/Senior ...

## Selenium advantages :
   - Using selenium we can depict a full fledged web browser.
   - This will help us to extract data from many pages of the same website.
   - So using various fuctions of selenium we can hover through all the pages and extract data from it.
   - Thus using selenium we can click on the buttons on a particular website to perform certain action from remote user.
   - In the below code we are finding elements by class name which consists of button, and the clicking on the button using .click()
   - In this way we can build a full fledged web browser and control it form remote user using selenium.

In [22]:
url1 = "https://www.naukri.com/data-science-jobs"
browser.get(url1)


# btns1 will contain a list of all the buttons which is present in the web page.
btns1=browser.find_elements_by_class_name("grayBtn")

btns1

## Creating Final Dataframe :
   -  This dataframe will contain all the informations scrapped using the above user defined function.
   - In the below code we are first creating an empty dictionary with key and value pair.
   - Keys will be the page numbers and values will be the data frame corresponding to the particular page.
   - We are using the .click() function to hover through the pages and extract data.
   - so the resultant dictionary will consist of many dataframes with desired information scrapped from all the pages.

In [24]:
url2 = "https://www.naukri.com/data-science-jobs-{}"

main={}

for i in range(1,5):
    main[i]=get_jos(url2.format(i))
    
    btns2=browser.find_elements_by_class_name("grayBtn")
    for i in btns2:
        if i== "NEXT":
             btns2.click()

In [29]:
# This is the datframe created from the data extracted from the 1st page of tghe naukri website,stored in the ductionary
main[1]

,company,salary,experience,location,designation
0,NOVARTIS HEALTHCARE PVT. LTD.,Not disclosed,10,Hyderabad,Manager Data Science and Analytics
1,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
2,CUNESOFT,Not disclosed,5,Bengaluru,Senior Software Developer - Nlp/machine Learni...
3,DCG DATA-CORE SYSTEMS (INDIA) PVT. LTD.,Not disclosed,9,United States (U.S),Machine Learning / Data Science - USA Opportu...
4,MAVEN WAVE PARTNERS (INDIA)PVT. LTD.,Not disclosed,6,"Gurgaon, Chandigarh",Data Science Lead
5,SAMATRIX CONSULTING PRIVATE LIMITED,Not disclosed,3,"Gurgaon, Noida, Delhi NCR","Machine Learning, Data Science Trainer"
6,MERITUS INTELYTICS PRIVATE LIMITED,Not disclosed,2,Hyderabad,Merilytics - Manager - Data Science - Iit/bits...
7,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,8,Bengaluru,Data Science Senior Advisor
8,SAPIENT CONSULTING PVT. LTD,Not disclosed,8,Bengaluru,Director-data Science
9,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,5,Bengaluru,Consultant Data Science
10,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
11,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
12,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
13,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
14,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
15,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering Unit...
16,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
17,MARSIAN TECHNOLOGIES LLP,Not disclosed,5,Pune(Viman Nagar),Data Science Trainer - Part Time
18,GO-JEK,Not disclosed,9,Bengaluru,Head of Data Science - Search
19,CLUSTR,Not disclosed,4,Bengaluru,Data Science Specialist / Sr. Data Scientist
20,ALLY-EXECUTIVE,Not disclosed,2,Mumbai,Product Manager - Data Science
21,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Bengaluru,Data Science
22,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
23,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
24,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
25,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,4,Bengaluru,Data Science
26,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
27,SAPIENT CONSULTING PVT. LTD,Not disclosed,8,Gurgaon,Director- Data Science
28,EMERSON ELECTRIC CO (I) PVT LTD,Not disclosed,3,Pune,Data Science Engineer
29,GARTNER INDIA RESEARCH & ADVISORY SERVICES PVT...,Not disclosed,3,Gurgaon,Business Analyst - Data Science
30,MEESHO,Not disclosed,4,Bengaluru,Senior Product Manager - Data Science/machine ...
31,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,7,Bengaluru,"Sr Advisor, Data Science"
32,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
33,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science Platform
34,GO-JEK,Not disclosed,8,Bengaluru,Head of Data Science
35,GO-JEK,Not disclosed,10,Bengaluru,Head of Data Science
36,WISSDA INC,Not disclosed,2,Pune,Principal Engineer - Data Science /machine Lea...
37,LARSEN & TOUBRO INFOTECH LIMITED,Not disclosed,4,"Chennai, Hyderabad",LTI Hiring- Data Science Professionals - 7th D...
38,NEXT LEVEL BUSINESS SERVICES,Not disclosed,20,"Bengaluru, Gurgaon",Senior Director - Data Science
39,ZF INDIA PRIVATE LIMITED,Not disclosed,6,Hyderabad,Data Science Manager in at ZF
40,REYBHAV TECHNOLOGIES PRIVATE LIMITED,Not disclosed,1,"Jaipur, Bengaluru","Automation Test, React Native, Dev Ops and Dat..."
41,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,8,Bengaluru,"Senior Analyst, Data Science"
42,REACHMENTOR,Not disclosed,2,Hosur,Trainer For Data Science
43,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
44,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
45,BAJAJ FINSERV LENDING LTD,Not disclosed,4,Pune,Cluster Manager - Data Science & Engineering/S...
46,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
47,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
48,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Unit Manager - Data Science & Engineering/Seni...
49,BAJAJ FINSERV LENDING LTD,Not disclosed,3,Pune,Lead - Data Science & Engineering Unit/Senior ...

In [31]:
# Here we are concating all the dataframes present in the above formed dictionary for further analysis. 

import pandas as pd
big_data1= pd.concat([main[i] for i in main],axis =0)

In [32]:
# Reseting the index of the above formed final data frame consisting of information stored in it extracted from all the pages.

big_data1=big_data1.reset_index()
big_data1.drop("index",inplace=True,axis=1)

In [33]:
# Final dataframe

big_data1

,company,salary,experience,location,designation
0,NOVARTIS HEALTHCARE PVT. LTD.,Not disclosed,10,Hyderabad,Manager Data Science and Analytics
1,CAPGEMINI TECHNOLOGY SERVICES INDIA LIMITED,Not disclosed,2,Gurgaon,Data Science and Analytics
2,CUNESOFT,Not disclosed,5,Bengaluru,Senior Software Developer - Nlp/machine Learni...
3,DCG DATA-CORE SYSTEMS (INDIA) PVT. LTD.,Not disclosed,9,United States (U.S),Machine Learning / Data Science - USA Opportu...
4,MAVEN WAVE PARTNERS (INDIA)PVT. LTD.,Not disclosed,6,"Gurgaon, Chandigarh",Data Science Lead
...,...,...,...,...,...
195,DELL INTERNATIONAL SERVICES INDIA PRIVATE LIM...,Not disclosed,5,Bengaluru,Sr.advisor: CCO Audience Strategy - Data Science
196,DIGITAL SPIRIT,Not disclosed,0,"Delhi NCR, Indore",Freshers To Experienced in Big Data / Data Sci...
197,V V COLLEGE OF ENGINEERING,Not disclosed,1,Tirunelveli,Data Science and Analytics
198,DUNNHUMBY INDIA PVT LTD,Not disclosed,2,Gurgaon,Senior Data Science Engineer
199,CUNESOFT,Not disclosed,4,Bengaluru,Sr Software Developer - NLP- ML- Data Science